steps:
    step1:
      name: Проверка создания организации
      request:
        header:
         messageType: GW.CREATE.REQ
         infoBrokerId: e248ad9d-9ed9-477a-b7a6-4c434f590b3f
        body:
         documentID: ba07755-56ff-42c9-b904-e2e506231f5d
         refDocumentID: 123
         participantMode: ED
         organizationInfo:
            title: Сбер
            inn: 7707083893
            kpp: 783502001
            ogrn: 1027700132195
            adress: Ленина 1
         participantInfo:
            docBasisType: REQUEST
            docBasisNumber: 1
      response:
        header:
          messageType: GW.CREATR.RES